name: lmm_pos
description: "POS Project by Oudomsak PHABOUDY"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #!------------------------------------------------------------------------------------------
  #! initail pub dev project
  #!------------------------------------------------------------------------------------------
  sizer: ^2.0.15
  get: ^4.6.6
  dio: ^5.4.3+1
  get_storage: ^2.1.1
  easy_localization: ^3.0.7
  #------------------------------------------------------------------------------------------
  # format
  #------------------------------------------------------------------------------------------
  intl: ^0.18.1
  #------------------------------------------------------------------------------------------
  # more
  #------------------------------------------------------------------------------------------
  pretty_qr_code: ^3.3.0
  cached_network_image: ^3.3.1
  qr_code_scanner: ^1.0.1
  animate_do: ^3.3.4
  keyboard_attachable: ^2.2.0
  lottie: ^3.1.1
  # device_info_plus: ^9.1.2
  google_fonts: ^4.0.0
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  iconsax: ^0.0.8
  awesome_bottom_bar: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/locales/
    - assets/lotties/
